"\n# Create an issue\n# labels are optional\n- type: issue\n  action: create\n  repo:\
  \ CMPSC-203-Allegheny-College-Fall-2022/Tier-comparison\n  title: Green Tier\n \
  \ body: This is the green tier. You are doing great!\n  labels:\n    - SheetShuttle\n\
  \    - Automated\n"
